title: "Name of event [City, 2letterCountryCode] (YYYY-MM-DD)"
body:
- type: textarea
  label: info
  attributes:
    description: |
    **Where:** 
    **When:** 
    **URL:** 
    <!--Add more info, including a picture (you can drag and drop from your file explorer)-->
  validations:
    required: true
