title: "Name of event [City, 2letterCountryCode] (YYYY-MM-DD)"
body:
- type: textarea
  attributes:
    label: info
    description: |
      **Where:** 
      **When:** 
      **URL:** 
      <!--Add more info, including a picture (you can drag and drop from your file explorer)-->
  validations:
    required: true
